### ISSUE TITLE
Disabling plugins

### ISSUE THREAD

**Issue by elifoster** [elifoster/SatanicBot#75]
Plugins should be able to be enabled/disabled in the YAML config file.

``` yaml
Enabled:
  - ModuleName
Disabled:
  - ModuleName2
```
